apiVersion: v1 
kind: Service
metadata:
  name: svc-pod-1
spec: 
  type: NodePort
  ports:
    - port: 80 # despacha pra essa
      # targetPort: 80 # escuta nessa do pod
      nodePort: 30000
  selector:
    app: primeiro-pod